### ISSUE TITLE
CI fails on all branches due to MongoDB failure

### ISSUE THREAD

**Issue by michaelKurowski** [michaelKurowski/lokim2#193]
**Describe the bug**
CI fails on all branches

```
  1) application startup
       should connect to db without errors:
     Uncaught Error: Failed to connect to database with host "localhost". Error: Error: connect ECONNREFUSED 127.0.0.1:27017
      at NativeConnection.db.on.err (connectToDb.js:15:9)
      at process.nextTick (node_modules/mongoose/lib/connection.js:624:37)
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

**To Reproduce**
Run CI on any commit

**Additional context**
Fails even for commits that used to pass.

**Comment by michaelKurowski** [comment]
Issue fixed on its own.
